# Generated by Django 5.2.8 on 2025-11-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_payment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Идентификатор сессии",
            ),
        ),
    ]
