# Generated by Django 5.2.8 on 2025-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Статус платежа"
            ),
        ),
    ]
