name: Django CI/CD

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.2
          virtualenvs-create: true
          virtualenvs-in-project: true # Creates a .venv folder in the project root

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: .venv # The path depends on the virtualenvs-in-project setting
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        run: poetry install --with lint --no-root

      - name: Run Flake8
        run: poetry run python -m flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      SECRET_KEY: "ci-test-key"
      USE_SQLITE: "True"

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.1.2
        virtualenvs-create: true
        virtualenvs-in-project: true # Creates a .venv folder in the project root

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: .venv # The path depends on the virtualenvs-in-project setting
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true' # Only run install if the cache is missed
      run: poetry install --no-interaction --no-root

    - name: Run migrations
      run: poetry run python manage.py migrate

    - name: Run tests
      run: poetry run python manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /myapp
            
            # Обновляем тег образа в .env или через переменную
            export IMAGE_TAG=${{ github.sha }}
            
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker-compose pull
            docker-compose up -d
            docker image prune -f # Чистим старые образы
          EOF
